### ISSUE TITLE
GetRegistryByName fails when can not find the registry

### ISSUE THREAD

**Issue by Gigigotrek** [mittwald/goharbor-client#175]
**Describe the bug**
When you try to call ```GetRegistryByName``` but the registry does not exist, it crashes because tries to return the first value of an empty list.

**To Reproduce**
With a clean Harbor instance without any registries configured, try to call ```GetRegistryByName``` with a name that does not exist. It will return 

```
2023-09-08T09:48:33+02:00	INFO	Observed a panic in reconciler: runtime error: index out of range [0] with length 0	{"controller": "managed/registry.registries.provider-harbor.crossplane.io", "controllerGroup": "registries.provider-harbor.crossplane.io", "controllerKind": "Registry", "Registry": {"name":"foo"}, "namespace": "", "name": "foo", "reconcileID": "bd5e566e-a5ae-4f88-b8cc-9292a674cee9"}
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
```

**Expected behavior**
The call to ```GetRegistryByName``` when the registry does not exist should return the error ```ErrRegistryNotFound```.

**Log files** (optional)

```
test12023-09-08T09:48:33+02:00	INFO	Observed a panic in reconciler: runtime error: index out of range [0] with length 0	{"controller": "managed/registry.registries.provider-harbor.crossplane.io", "controllerGroup": "registries.provider-harbor.crossplane.io", "controllerKind": "Registry", "Registry": {"name":"foo"}, "namespace": "", "name": "foo", "reconcileID": "bd5e566e-a5ae-4f88-b8cc-9292a674cee9"}
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 175 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1a8
panic({0x1046f30e0, 0x140005b6180})
	runtime/panic.go:884 +0x204
github.com/mittwald/goharbor-client/v5/apiv2/pkg/clients/registry.(*RESTClient).GetRegistryByName(0x140003c1a40, {0x104858348, 0x14000a2b770}, {0x140007386b6?, 0x0?})
	github.com/mittwald/goharbor-client/v5@v5.4.1/apiv2/pkg/clients/registry/registry.go:92 +0x1f8
github.com/mittwald/goharbor-client/v5/apiv2.(*RESTClient).GetRegistryByName(0x104841440?, {0x104858348?, 0x14000a2b770?}, {0x140007386b6?, 0x1?})
	github.com/mittwald/goharbor-client/v5@v5.4.1/apiv2/client.go:401 +0x2c
provider-harbor/internal/controller/registry.(*external).Observe(0x140003c1ba0, {0x104858348, 0x14000a2b770}, {0x10486d890?, 0x140001f1180})
	provider-harbor/internal/controller/registry/registry.go:122 +0xc0
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0x1400081c3c0, {0x104858380, 0x14000a2b6b0}, {{{0x0, 0x0}, {0x14000988036, 0x3}}})
	github.com/crossplane/crossplane-runtime@v0.20.0-rc.0.0.20230413174155-c8cff1a7fb74/pkg/reconciler/managed/reconciler.go:805 +0x223c
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0x140003341e0, {0x104858380, 0x14000a2b6b0}, {{{0x0?, 0x30?}, {0x14000988036?, 0x12d3df301?}}})
	github.com/crossplane/crossplane-runtime@v0.20.0-rc.0.0.20230413174155-c8cff1a7fb74/pkg/ratelimiter/reconciler.go:54 +0x124
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x104858380?, {0x104858380?, 0x14000a2b6b0?}, {{{0x0?, 0x104499d80?}, {0x14000988036?, 0x104844ae0?}}})
	sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0x8c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x14000647040, {0x1048582d8, 0x140003701e0}, {0x104653280?, 0x1400049ad60?})
	sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x2c8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x14000647040, {0x1048582d8, 0x140003701e0})
	sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1b0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x448
make: *** [run] Error 2
```

Environment:
- `goharbor-client` 5.4.1
- `goharbor` v2.8.4-ad3e767d

**Comment by Gigigotrek** [comment]
We have created the [PR](https://github.com/mittwald/goharbor-client/pull/176) that should solve this issue.

**Comment by elenz97** [comment]
Fixed by https://github.com/mittwald/goharbor-client/pull/176.
